### ISSUE TITLE
Create a datasheet parser

### ISSUE THREAD

**Issue by astralien3000** [astralien3000/aversive--#5]
I know the coders of Aversive made one. That would be great to see if it is possible to make one by ourselves because writing .archi files by hand is an heavy process !

**Comment by astralien3000** [comment]
Hey !
I have found some news about archi files. Indeed, currently, I have to write the ".archi" files by hand while reading the datasheets, which is very long and can create bugs.
But the AtmelStudio software provides some XML files that describe the registers quite in the same way I want the ".archi" files to. It can greatly accelerate the port of Aversive++ on all AVRs !!

You can see the xml files here : 
https://www.dropbox.com/s/jkb7ld961tcn22w/devices.zip?dl=0

This is a solution of issues #9, #37, and this one.

**Comment by Elioty** [comment]
Very very nice discovery!

So this is indeed a solution to get rid of avr-libc dependency, at least for all the MCU's macro definitions. We still have to get our own malloc functions implementation, float operation functions and trigonometry functions but we would probably just import them from avr-libc.

For issue #37, it isn't really a solution as we still have to make a parser, but it would get those xml files as input instead of our archi files.

Now I am thinking, can't we find similar files for other MCUs like the STM32-f4 and other ARM chips?
And should we create a new issue or rename this one (and probably add the AVR label) to talk more precisely of parsing those xml files (instead of the whole raw datasheets)?

**Comment by astralien3000** [comment]
Here are others XML files for AVRs and some STM32, and even some other ARMs !
It comes from a project of Eclipse IDE.

http://sourceforge.net/p/embsysregview/code/HEAD/tree/trunk/org.eclipse.cdt.embsysregview.data/data/

Maybe i can find an other more "official" source.
